export const db = [
  {
    id: 1,
    projectId: 1,
    projectCode: 'PRJCKB-001',
    task: 'Testing Commissioning',
    department: 'PROJECT',
    vendor: 'PT KIA',
    startDate: '2026-06-29',
    endDate: '2026-07-12',
    status: 'Waiting',
    progress: 40,
    pic: 'Alif',
    priority: 'High',
    assignedTo: 'Alif',
    taskCategory: 'Commissioning',
    plannedHours: 24,
    actualHours: 10,
    remarks: 'Menunggu material tambahan'
  },
  {
    id: 2,
    projectId: 1,
    projectCode: 'PRJCKB-001',
    task: 'Balancing',
    department: 'PROJECT',
    vendor: 'PT KIA',
    startDate: '2026-06-29',
    endDate: '2026-07-12',
    status: 'Ongoing',
    progress: 75,
    pic: 'Alif',
    priority: 'Medium',
    assignedTo: 'Alif',
    taskCategory: 'Testing',
    plannedHours: 18,
    actualHours: 12,
    remarks: 'Sedang proses pengaturan sistem'
  },
  {
    id: 3,
    projectId: 2,
    projectCode: 'PRJCKB-002',
    task: 'Install Piping',
    department: 'PROJECT',
    vendor: 'PT GAMINDO',
    startDate: '2026-07-01',
    endDate: '2026-07-20',
    status: 'Planned',
    progress: 10,
    pic: 'Budi',
    priority: 'High',
    assignedTo: 'Budi',
    taskCategory: 'Installation',
    plannedHours: 30,
    actualHours: 3,
    remarks: 'Persiapan bahan dan jadwal'
  },
  {
    id: 4,
    projectId: 2,
    projectCode: 'PRJCKB-002',
    task: 'Material Delivery Check',
    department: 'PROJECT',
    vendor: 'PT GAMINDO',
    startDate: '2026-07-02',
    endDate: '2026-07-04',
    status: 'Ongoing',
    progress: 50,
    pic: 'Citra',
    priority: 'Medium',
    assignedTo: 'Citra',
    taskCategory: 'Logistics',
    plannedHours: 10,
    actualHours: 5,
    remarks: 'Vendor sudah kirim separuh material'
  }
]
